apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  annotations:
    description: "Configmap para o banco de dados do projeto lanchonetebairro"
data:
  MYSQL_ROOT_USERNAME: "root"
  MYSQL_ROOT_PASSWORD: "senha"
  MYSQL_URL: "lanchonetebairro.cqvrfpmeh0xq.us-east-1.rds.amazonaws.com"
