# apiVersion: v1
# kind: Secret
# metadata:
#   name: db-secret
#   annotations:
#     description: "Secret para o banco de dados do projeto lanchonetebairro"
# stringData:
#   MYSQL_ROOT_PASSWORD: "senha"
