apiVersion: v1
kind: Service
metadata:
  name: maria-db
  labels:
    app: maria-db
  annotations:
    description: "Service do banco de dados do projeto lanchonetebairro"
spec:
  type: ClusterIP
  selector:
    app: maria-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306